persistence:
  config:
    storageClass: "longhorn"
  media:
    storageClass: "longhorn-special-disk"
    size: 850Gi
    accessMode: ReadWriteMany
podSecurityContext:
  fsGroup: 1000
securityContext:
  runAsUser: 1000
  runAsGroup: 1000

metrics:
  enabled: true
  serviceMonitor:
    enabled: true

# Standard Helm chart syntax
startupProbe:
  failureThreshold: 30
  periodSeconds: 10

# OR bjw-s app-template syntax
probes:
  startup:
    spec:
      failureThreshold: 30
      periodSeconds: 10

dnsPolicy: "ClusterFirst"
dnsConfig:
  nameservers:
    - "1.1.1.1"
  options:
    - name: ndots
      value: "5"
